const GET_CART = 'cart/GET_CART'
const GET_CART_REJECTED = 'cart/GET_CART_REJECTED'

const ADD_TO_CART = 'cart/ADD_TO_CART'
const ADD_TO_CART_REJECTED = 'cart/ADD_TO_CART_REJECTED'

const DELETE_FROM_CART = 'cart/DELETE_FROM_CART'
const DELETE_FROM_CART_REJECTED = 'cart/DELETE_FROM_CART_REJECTED'

const UPDATE_BOOK_QUANTITY_IN_CART = 'cart/UPDATE_BOOK_QUANTITY_IN_CART'
const UPDATE_BOOK_QUANTITY_IN_CART_REJECTED = 'cart/UPDATE_BOOK_QUANTITY_IN_CART_REJECTED'

export {
  GET_CART, GET_CART_REJECTED,
  ADD_TO_CART, ADD_TO_CART_REJECTED,
  DELETE_FROM_CART, DELETE_FROM_CART_REJECTED,
  UPDATE_BOOK_QUANTITY_IN_CART, UPDATE_BOOK_QUANTITY_IN_CART_REJECTED
}
