const GET_BOOK_LIST = 'book/GET_BOOK_LIST'
const GET_BOOK_LIST_REJECTED = 'book/GET_BOOK_LIST_REJECTED'
const POST_BOOK = 'book/POST_BOOK'
const POST_BOOK_REJECTED = 'book/POST_BOOK_REJECTED'
const UPDATE_BOOK_TITLE = 'book/UPDATE_BOOK_TITLE'
const DELETE_BOOK = 'book/DELETE_BOOK'
const DELETE_BOOK_REJECTED = 'book/DELETE_BOOK_REJECTED'

export { GET_BOOK_LIST, GET_BOOK_LIST_REJECTED,
  POST_BOOK, POST_BOOK_REJECTED,
  UPDATE_BOOK_TITLE,
  DELETE_BOOK, DELETE_BOOK_REJECTED
}
