const SAVE_BUTTON_PRESSED = 'bookForm/SAVE_BUTTON_PRESSED'
const SAVE_BUTTON_RESET = 'bookForm/SAVE_BUTTON_RESET'

const SAVE_ACTION_ACCEPTED = 'bookForm/SAVE_ACTION_ACCEPTED'
const SAVE_ACTION_REJECTED = 'bookForm/SAVE_ACTION_REJECTED'

export {
  SAVE_BUTTON_PRESSED, SAVE_BUTTON_RESET,
  SAVE_ACTION_ACCEPTED, SAVE_ACTION_REJECTED
}
